kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: sample-backend-canary
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: sample
        role: backend
        env: canary
    spec:
      containers:
      - name: backend
        image: {{ .Values.app.image }}
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        env:
        - name: COMPONENT
          value: backend
        - name: VERSION
          value: canary
        ports:
        - name: backend
          containerPort: 8080
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: sample-backend-production
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 4
  template:
    metadata:
      name: backend
      labels:
        app: sample
        role: backend
        env: production
    spec:
      containers:
      - name: backend
        image: {{ .Values.app.image }}
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        env:
        - name: COMPONENT
          value: backend
        - name: VERSION
          value: production
        ports:
        - name: backend
          containerPort: 8080
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: sample-frontend-canary
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: sample
        role: frontend
        env: canary
    spec:
      containers:
      - name: frontend
        image: {{ .Values.app.image }}
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        env:
        - name: COMPONENT
          value: frontend
        - name: BACKEND_URL
          value: http://sample-backend-canary:8080/metadata
        - name: VERSION
          value: canary
        ports:
        - name: frontend
          containerPort: 8080
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: sample-frontend-production
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 4
  template:
    metadata:
      name: frontend
      labels:
        app: sample
        role: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: {{ .Values.app.image }}
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        env:
        - name: COMPONENT
          value: frontend
        - name: BACKEND_URL
          value: http://sample-backend-production:8080/metadata
        - name: VERSION
          value: production
        ports:
        - name: frontend
          containerPort: 8080                  
